---
title: "First Knit"
author: "Aeilani Felix"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     

I attended Lancaster & Palmdale High School.I graduated the year of 2023 and I feel like English was way better than math. My favorite subject was Anatomy though.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   I will be working off of my Ipad. I suppose that I can possibly be a 9/10 with knowing about technology. I have very good internet where I stay.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I pefer to be called Lani , it is was easier than pronouncing my whole name.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
  My dream is to become a traveling nurse. I think I would find the nursing classes more interesting then others being that , that is what I'm more interested in. The goal I am reaching for would be to obtain my RN license!
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer      
  
  No I haven't, but if I were to travel I would definitely like to go to Mexico, Italy , Greece , Dubai , Japan and many more. I plan on traveling the world when I graduate! I have never been in the military , but I have a lot of family member who have been.  
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
  I did not know that, but now I do! I plan on passing this class with a A. If not an A then a B will be okay. Being that I want to become a nurse I have to do good because if I fail, it wont be so good. 
 






  




